local cb = require('colorbuddy.init')
local Color = cb.Color
local colors = cb.colors
local Group = cb.Group
local groups = cb.groups
local styles = cb.styles
local cError = groups.Error.fg
local cInfo = groups.Information.fg
local cWarn = groups.Warning.fg
local cHint = groups.Hint.fg

Color.new('red','#e63022')
Color.new('orange','#d35400')
Color.new('brown','#9f6b3f')
Color.new('yellow','#daa520')
Color.new('lightgrey','#6c7a89')
Color.new('hardgrey','#d2d7d3')
Color.new('grey','#aaaaaa')
Color.new('purple','#e000e0')
Color.new('cyan','#00f8fb')
Color.new('blue','#1e90ff')
Color.new('green','#00aa00')
Color.new('cursorline','#222222')
Color.new('black','#000000')
Color.new('menu','#555555')
Color.new('menuSel','#444444')


Group.new('@include', colors.red, colors.NONE, styles.NONE)
Group.new('@string', colors.grey, colors.NONE, styles.NONE)
Group.new('@namespace', colors.green, colors.NONE, styles.NONE)
Group.new('@type', colors.orange, colors.NONE, styles.NONE)
Group.new('@keyword', colors.yellow, colors.NONE, styles.NONE)
Group.new('@field', colors.blue, colors.NONE, styles.NONE)
Group.new('@type.builtin', colors.green, colors.NONE, styles.NONE)
Group.new('@type.definition', colors.green, colors.NONE, styles.NONE)
Group.new('@punctuation.delimiter', colors.hardgrey, colors.NONE, styles.NONE)
Group.new('@punctuation.bracket', colors.red, colors.NONE, styles.NONE)
Group.new('@comment', colors.lightgrey, colors.NONE, styles.NONE)
Group.new('@operator', colors.yellow, colors.NONE, styles.NONE)
Group.new('@constant', colors.blue, colors.NONE, styles.NONE)
Group.new('@keyword.function', colors.green, colors.NONE, styles.italic)
Group.new('@function', colors.orange, colors.NONE, styles.NONE)
Group.new('@parameter', colors.blue, colors.NONE, styles.NONE)
Group.new('@number', colors.hardgrey, colors.NONE, styles.NONE)
Group.new('@operator', colors.red, colors.NONE, styles.NONE)
Group.new('@variable', colors.hardgrey, colors.NONE, styles.NONE)
Group.new('@function.call', colors.green, colors.NONE, styles.italic)
Group.new('@conditional', colors.cyan, colors.NONE, styles.italic)
Group.new('@repeat', colors.cyan, colors.NONE, styles.italic)
Group.new('@constant.builtin', colors.red, colors.NONE, styles.italic)
Group.new('@keyword.return', colors.yellow, colors.NONE, styles.italic)
Group.new('@method', colors.orange, colors.NONE, styles.NONE)
Group.new('@property', colors.orange, colors.NONE, styles.NONE)
Group.new('@method.call', colors.green, colors.NONE, styles.italic)
Group.new('@function.builtin', colors.cyan, colors.NONE, styles.italic)
Group.new('CursorLine', colors.NONE, colors.cursorline, styles.NONE)
Group.new('Pmenu', colors.NONE, colors.menu, styles.NONE)
Group.new('NormalFloat', colors.NONE, colors.NONE, styles.NONE)
Group.new('PmenuSel', colors.NONE, colors.menuSel, styles.NONE)
Group.new('PmenuSbar', colors.NONE, colors.NONE, styles.NONE)
Group.new('PmenuThumb', colors.NONE, colors.NONE, styles.NONE)
Group.new('TabLine', colors.black, colors.grey, styles.NONE)
Group.new('Normal', colors.NONE, colors.NONE, styles.NONE)
Group.new('CursorLineNr', colors.orange, colors.black, styles.NONE, colors.black)
Group.new('LineNr', colors.yellow, colors.NONE, styles.NONE, colors.black)
Group.new('Visual', colors.NONE, colors.black, styles.reverse)
Group.new("DiagnosticVirtualTextError", colors.red, colors.NONE, styles.NONE)
Group.new("DiagnosticVirtualTextInfo", colors.yellow, colors.NONE, styles.NONE)
Group.new("DiagnosticVirtualTextWarn", colors.orange, colors.NONE, styles.NONE)
Group.new("DiagnosticVirtualTextHint", colors.cyan, colors.NONE, styles.NONE)
Group.new("DiagnosticVirtualTextHint", colors.cyan, colors.NONE, styles.NONE)
Group.new("Nontext", colors.cyan, colors.NONE, styles.NONE)
Group.new("Matchparen", colors.NONE, colors.NONE, styles.reverse)
Group.new("Whitespace", colors.black, colors.NONE, styles.NONE)
Group.new("EndOfBuffer", colors.black, colors.NONE, styles.NONE)
Group.new("GitSignsCurrentLineBlame", colors.cyan, colors.NONE, styles.NONE)
Group.new("DiffChange", colors.blue, colors.NONE, styles.NONE)
Group.new("DiffAdd", colors.green, colors.NONE, styles.NONE)
Group.new("DiffDelete", colors.red, colors.NONE, styles.NONE)
Group.new("Search", colors.black, colors.cyan, styles.NONE)
Group.new("IncSearch", colors.black, colors.cyan, styles.NONE)
Group.new("TelescopeNormal", colors.NONE, colors.NONE, styles.NONE)
Group.new("Constant", colors.grey, colors.NONE, styles.NONE)
Group.new("SignColumn", colors.grey, colors.NONE, styles.NONE)
Group.new("boolean", colors.grey, colors.NONE, styles.italic)
Group.new("CmpItemKindSnippet", colors.purple, colors.NONE, styles.italic)
Group.new("CmpItemKindMethod", colors.green, colors.NONE, styles.italic)
Group.new("CmpItemKindKeyword", colors.yellow, colors.NONE, styles.italic)
Group.new("CmpItemKindParameter", colors.blue, colors.NONE, styles.italic)
Group.new("CmpItemKindFunction", colors.green, colors.NONE, styles.italic)
Group.new("CmpItemKindVariable", colors.hardgrey, colors.NONE, styles.italic)
Group.new("CmpItemKindModule", colors.red, colors.NONE, styles.italic)
Group.new("CmpItemKindStruct", colors.orange, colors.NONE, styles.italic)
Group.new("CmpItemKindInterface", colors.yellow, colors.NONE, styles.italic)
Group.new("CmpItemKindField", colors.blue, colors.NONE, styles.italic)
Group.new("Cursor", colors.black, colors.gray, styles.NONE)
Group.new("TermCursor", colors.black, colors.hardgrey, styles.NONE)
